version: 2
root-markers:
  - .git/

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
  eslint: &eslint
    lint-command: 'eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true
  tslint: &tslint
    lint-command: 'tslint -p ./tsconfig.json'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c - %m'
  prettier: &prettier
    format-command: 'prettier'
  luafmt: &lua-format
    format-command: 'lua-format -i'
    format-stdin: true

languages:
  vim:
    - <<: *vim-vint
  javascript:
    - <<: *eslint
  typescript:
    - <<: *eslint
    - <<: *tslint
  javascriptreact:
    - <<: *eslint
  typescriptreact:
    - <<: *eslint
    - <<: *tslint
  lua:
    - <<: *luafmt
