version: 2
root-markers:
  - .git/

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  prettier: &prettier
    format-command: './node_modules/.bin/prettier'

  terraform: &terraform
    format-command: 'terraform fmt -'
    format-stdin: true

  luafmt: &luafmt
    format-command: 'luafmt --stdin'
    format-stdin: true

  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  vim:
    - <<: *vim-vint
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  javascriptreact:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  yaml:
    - <<: *prettier
  json:
    - <<: *prettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  markdown:
    - <<: *prettier
  tf:
    - <<: *terraform
  lua:
    - <<: *luafmt
  sh:
    - <<: *shellcheck
