version: 2
root-markers:
  - .git/

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
  eslint: &eslint
    lint-command: 'eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true
  tslint: &tslint
    lint-command: 'tslint -p ./tsconfig.json'
    lint-ignore-exit-code: true
    lint-stdin: true
  prettier: &prettier
    format-command: 'prettier'
  terraform: &terraform
    format-command: 'terraform fmt -'
    format-stdin: true
  luafmt: &luafmt
    format-command: 'luafmt --stdin'
    format-stdin: true
  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  vim:
    - <<: *vim-vint
  javascript:
    - <<: *eslint
  typescript:
    - <<: *eslint
    - <<: *tslint
  javascriptreact:
    - <<: *eslint
  typescriptreact:
    - <<: *eslint
    - <<: *tslint
  tf:
    - <<: *terraform
  lua:
    - <<: *luafmt
  sh:
    - <<: *shellcheck
