version: 2
log-file: './efm.log'
log-level: 2
root-markers:
  - .git/
  - package.json

tools:
  vim-vint: &vim-vint
    lint-command: 'vint -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'
  eslint: &eslint
    lint-command: 'eslint -f unix --stdin --stdin-filename'
    lint-ignore-exit-code: true
    lint-stdin: true
  tslint: &tslint
    lint-command: 'tslint -p ./tsconfig.json'
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c - %m'
  prettier: &prettier
    format-command: 'prettier'
  lua-format: &lua-format
    format-command: 'lua-format -i'
    format-stdin: true

languages:
  vim:
    - <<: *vim-vint
  lua:
    - <<: *lua-format
  javascript:
    - <<: *eslint
  typescript:
    - <<: *eslint
    - <<: *tslint
  javascriptreact:
    - <<: *eslint
  typescriptreact:
    - <<: *eslint
    - <<: *tslint
