
colors:
  line_indicator:
    background: "#50494E"
    foreground: "None"
  vi_mode_cursor:
    text: "CellBackground"
    cursor: "CellForeground"
  normal:
    white: "#EBCCAD"
    cyan: "#6BC7BF"
    black: "#281D30"
    magenta: "#561DC9"
    blue: "#1D64C9"
    green: "#36633D"
    red: "#A3293D"
    yellow: "#FFBB33"
  search:
    focused_match:
      background: "CellForeground"
      foreground: "CellBackground"
    matches:
      background: "#ffffff"
      foreground: "#000000"
    bar:
      background: "#ebccad"
      foreground: "#1a141f"
  primary:
    background: "#1A141F"
    bright_foreground: "#FBF7E9"
    dim_foreground: "#A38FA0"
    foreground: "#EBCCAD"
  dim:
    white: "#E6BF99"
    cyan: "#50958F"
    black: "#42334D"
    magenta: "#412A6F"
    blue: "#506D95"
    green: "#8AA88F"
    red: "#AF6A75"
    yellow: "#C38E22"
  bright:
    white: "#FBF7E9"
    cyan: "#D6F5F2"
    black: "#50494E"
    magenta: "#AF8FEF"
    blue: "#4C8CE6"
    green: "#789550"
    red: "#FA9E9E"
    yellow: "#FFD480"
  selection:
    text: "CellBackground"
    background: "CellForeground"
  cursor:
    text: "CellBackground"
    cursor: "CellForeground"