
colors:
  line_indicator:
    foreground: "None"
    background: "#50494E"
  vi_mode_cursor:
    cursor: "CellForeground"
    text: "CellBackground"
  normal:
    cyan: "#6BC7BF"
    black: "#281D30"
    magenta: "#561DC9"
    blue: "#1D64C9"
    green: "#36633D"
    red: "#A3293D"
    yellow: "#FFBB33"
    white: "#EBCCAD"
  selection:
    background: "CellForeground"
    text: "CellBackground"
  primary:
    bright_foreground: "#FBF7E9"
    dim_foreground: "#A38FA0"
    foreground: "#EBCCAD"
    background: "#1A141F"
  hints:
    end:
      foreground: "#e9ff5e"
      background: "#1d1f21"
    start:
      foreground: "#1d1f21"
      background: "#e9ff5e"
  search:
    bar:
      background: "#ebccad"
      foreground: "#1a141f"
    focused_match:
      foreground: "CellBackground"
      background: "CellForeground"
    matches:
      foreground: "#000000"
      background: "#ffffff"
  dim:
    cyan: "#50958F"
    black: "#42334D"
    magenta: "#412A6F"
    blue: "#506D95"
    green: "#8AA88F"
    red: "#AF6A75"
    yellow: "#C38E22"
    white: "#E6BF99"
  cursor:
    cursor: "CellForeground"
    text: "CellBackground"
  bright:
    cyan: "#D6F5F2"
    black: "#50494E"
    magenta: "#AF8FEF"
    blue: "#4C8CE6"
    green: "#789550"
    red: "#FA9E9E"
    yellow: "#FFD480"
    white: "#FBF7E9"