
colors:
  primary:
    background: "#1A141F"
    bright_foreground: "#FBF7E9"
    foreground: "#EBCCAD"
    dim_foreground: "#A38FA0"
  line_indicator:
    foreground: "None"
    background: "#50494E"
  selection:
    background: "CellForeground"
    text: "CellBackground"
  search:
    bar:
      background: "#ebccad"
      foreground: "#1a141f"
    focused_match:
      foreground: "CellBackground"
      background: "CellForeground"
    matches:
      foreground: "#000000"
      background: "#ffffff"
  cursor:
    cursor: "CellForeground"
    text: "CellBackground"
  dim:
    white: "#E6BF99"
    cyan: "#50958F"
    red: "#AF6A75"
    yellow: "#C38E22"
    green: "#8AA88F"
    black: "#42334D"
    blue: "#506D95"
    magenta: "#412A6F"
  normal:
    white: "#EBCCAD"
    cyan: "#6BC7BF"
    red: "#A3293D"
    yellow: "#FFBB33"
    green: "#36633D"
    black: "#281D30"
    blue: "#1D64C9"
    magenta: "#561DC9"
  vi_mode_cursor:
    cursor: "CellForeground"
    text: "CellBackground"
  bright:
    white: "#FBF7E9"
    cyan: "#D6F5F2"
    red: "#FA9E9E"
    yellow: "#FFD480"
    green: "#789550"
    black: "#50494E"
    blue: "#4C8CE6"
    magenta: "#AF8FEF"